title: 'zero-plastic-list.de'
author:
  name: 'Leon Weickert'
  email: 'zeroplastic@einfach123.de'
metadata:
    description: "Get a list of products that don't contain any (or less) plastic. We will extend this list from time to time."

